CDAP-19589 - Add sort for reliable ordering of CDC events
data-integrations/delta pull request #188
Opened 2022-09-13 05:28 UTC by sumitjnn

2022-09-16 16:42 UTC, sahusanket requested changes
We will not add sort keys to DDL events?

2022-09-16 17:00 UTC, sumitjnn commented
> We will not add sort keys to DDL events?

No, sort keys are not DDL events are applied immediately and do not require ordering.

2022-09-16 17:18 UTC, seanzhougoogle approved these changes

2022-09-16 17:52 UTC, seanzhougoogle commented
> > We will not add sort keys to DDL events?
> 
> No, sort keys are not required for DDL events as they are applied immediately and do not require ordering.

Mainly it's because DDL events are not generated from Datastream, we generate the DDL events in order ourselves.

2022-09-17 09:22 UTC, sahusanket approved these changes

2022-09-23 08:22 UTC, merged