Throw DeltaFailureRuntimeException when pipeline is run without prima…
data-integrations/delta pull request #193
Opened 2022-11-10 08:21 UTC by yjhawar

…ry key in table.

-Added DeltaFailureRuntimeException.
- Fail the pipeline throwing DeltaFailureRuntimeException, when it is run without primary key in a table.
Link to the JIRA bug: https://cdap.atlassian.net/browse/CDAP-19607.

2022-11-11 11:17 UTC, sumitjnn approved these changes

2022-11-11 11:17 UTC, sumitjnn commented on delta-api/src/main/java/io/cdap/delta/api/DeltaFailureRuntimeException.java
> + * Copyright © 2020 Cask Data, Inc.
Nit: change year

2022-11-14 10:51 UTC, sumitjnn requested changes

2022-11-14 10:51 UTC, sumitjnn commented on delta-app/src/test/java/io/cdap/delta/app/DeltaWorkerTest.java
> +      throw e;
Why do we need this, we are just rethrowing the exception here

2022-11-14 10:51 UTC, sumitjnn commented on delta-app/src/test/java/io/cdap/delta/app/appSpec-config.json
> +          "password": "test@123"
let's put dummy values here instead of real ones

2022-11-14 12:42 UTC, sumitjnn approved these changes

2022-11-14 15:55 UTC, sahusanket approved these changes

2022-11-15 10:09 UTC, merged